# Generated by Django 5.2.6 on 2025-10-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailattempt',
            options={'permissions': [('can_view_mailattempt', 'Can view mail attempt')]},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Can view mailing'), ('can_add_mailing', 'Can add mailing'), ('can_change_mailing', 'Can change mailing'), ('can_delete_mailing', 'Can delete mailing'), ('can_send_mailing', 'Can send mailing')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_message', 'Can view message'), ('can_add_message', 'Can add message'), ('can_change_message', 'Can change message'), ('can_delete_message', 'Can delete message')]},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_view_recipient', 'Can view recipient'), ('can_add_recipient', 'Can add recipient'), ('can_change_recipient', 'Can change recipient'), ('can_delete_recipient', 'Can delete recipient')]},
        ),
    ]
