# Generated by Django 5.2.6 on 2025-10-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailings.mailing'),
        ),
        migrations.AlterField(
            model_name='mailattempt',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailings.recipient'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailings.message'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='mailings', to='mailings.recipient'),
        ),
    ]
